config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users do
    resources :transactions
    resources :rewards do
      member do
        post 'claim'
      end
    end
  end

  # Defines the root path route ("/")
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reward.rb
class Reward < ApplicationRecord
    belongs_to :user
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user

  after_create :calculate_points_and_check_rewards_eligibility

  scope :in_month, ->(month) { where("extract(month from created_at) = ?", month) }

  private

  def calculate_points_and_check_rewards_eligibility
    points = amount / 100
    points *= 2 if foreign_transaction?
    user.update_points(points)
    user.update_monthly_points(created_at.month)
    user.check_rewards_eligibility(points)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :transactions
  has_many :rewards

  enum tier: { standard: 0, gold: 1, platinum: 2 }

  def birthday_month
    birthday&.month
  end

  def update_points(points)
    update(points: self.points + points)
    update_tier
  end

  def first_transaction_date
    transactions.order(created_at: :asc)&.first&.created_at
  end

  def expire_points
    update(points: 0, points_expiration: Date.today + 1.year)
  end

  def update_tier
    update(tier: :gold) if points >= 1000
    update(tier: :platinum) if points >= 5000
  end

  def check_rewards_eligibility(points)
    check_free_coffee_reward(points)
    check_free_coffee_birthday_reward
    check_cash_rebate_reward
    check_free_movie_tickets_reward
    check_gold_tier_reward
    check_quarterly_bonus_points
  end

  def update_monthly_points(month)
    transactions_this_month = transactions.in_month(month)
    monthly_points = transactions_this_month.sum(:amount) / 100 # Divide by 100 to get points
    update(monthly_points: monthly_points)
    check_free_coffee_reward(monthly_points)
  end

  private

  def check_free_coffee_reward(points)
    if points >= 100
      rewards.create(name: 'Free Coffee')
    end
  end

  def check_free_coffee_birthday_reward
    if birthday_month == Date.today.month
      rewards.create(name: 'Free Coffee (Birthday)')
    end
  end

  def check_cash_rebate_reward
    high_value_transactions_count = transactions.where('amount > ?', 100).count
    if high_value_transactions_count >= 10
      rewards.create(name: '5% Cash Rebate')
    end
  end

  def check_free_movie_tickets_reward
    if first_transaction_date.present? && transactions.where('created_at >= ? AND amount > ?', first_transaction_date + 60.days, 1000).exists?
      rewards.create(name: 'Free Movie Tickets')
    end
  end

  def check_gold_tier_reward
    if tier_changed? && tier == 'gold'
      rewards.create(name: '4x Airport Lounge Access')
    end
  end

  def check_quarterly_bonus_points
    quarter_start_date = Date.today.beginning_of_quarter
    quarter_end_date = Date.today.end_of_quarter
    total_spending_in_quarter = transactions.where(created_at: quarter_start_date..quarter_end_date).sum(:amount)
    if total_spending_in_quarter > 2000
      update_points(100)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
    def index
      @user = User.find(params[:user_id])
      @rewards = @user.rewards
    end
  
    def claim
      @reward = Reward.find(params[:id])
      if @reward.claimed_at.nil?
        @reward.update(claimed_at: Time.now)
        redirect_to user_rewards_path(@reward.user), notice: 'Reward claimed successfully.'
      else
        redirect_to user_rewards_path(@reward.user), alert: 'Reward has already been claimed.'
      end
    end

    def new
        @user = User.find(params[:user_id])
        @reward = @user.rewards.new
      end
    
      def create
        @user = User.find(params[:user_id])
        @reward = @user.rewards.new(reward_params)
        if @reward.save
          redirect_to user_rewards_path(@user), notice: 'Reward created successfully.'
        else
          render :new
        end
      end
    
      private
    
      def reward_params
        params.require(:reward).permit(:name)
      end
  end
  

app/controllers/tiers_controller.rb
class TiersController < ApplicationController
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    def index
      @user = User.find(params[:user_id])
      @transactions = @user.transactions
    end
  
    def new
      @user = User.find(params[:user_id])
      @transaction = @user.transactions.new
    end
  
    def create
      @user = User.find(params[:user_id])
      @transaction = @user.transactions.new(transaction_params)
      if @transaction.save
        redirect_to user_transactions_path(@user), notice: 'Transaction was successfully recorded.'
      else
        render :new
      end
    end
  
    private
  
    def transaction_params
      params.require(:transaction).permit(:amount, :foreign_transaction)
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
      @users = User.all
    end
  
    def show
      @user = User.find(params[:id])
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to @user, notice: 'User was successfully created.'
      else
        render :new
      end
    end
  
    private
  
    def user_params
      params.require(:user).permit(:name, :birthday, :first_transaction_date)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/tiers_helper.rb
module TiersHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoyaltyProgram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rewards/_form.html.erb
<%= form_with(model: [@user, @reward]) do |form| %>
  <% if @reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reward.errors.count, "error") %> prohibited this reward from being saved:</h2>
      <ul>
        <% @reward.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rewards/index.html.erb
<h1>My Rewards</h1>
<ul>
  <% @rewards.each do |reward| %>
    <li>
      <%= reward.name %>
      <% if reward.claimed_at %>
        (Claimed)
      <% else %>
        <%= link_to 'Claim', claim_user_reward_path(@user, reward), data: { confirm: 'Are you sure?', turbo_method: 'post' } %>
      <% end %>
    </li>
  <% end %>
</ul>
<%= link_to 'Back', user_path(@user) %>

app/views/rewards/new.html.erb
<h1>New Reward</h1>
<%= render 'form' %>
<%= link_to 'Back', user_rewards_path(@user) %>

app/views/rewards/show.html.erb
<h1>Reward Details</h1>
<p><strong>Name:</strong> <%= @reward.name %></p>
<p><strong>Claimed:</strong> <%= @reward.claimed_at ? 'Yes' : 'No' %></p>
<%= link_to 'Back', user_rewards_path(@reward.user) %>

app/views/transactions/_form.html.erb
<%= form_with(model: [@user, @transaction]) do |form| %>
    <% if @transaction.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>
        <ul>
          <% @transaction.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= form.label :amount %>
      <%= form.text_field :amount %>
    </div>
    <div class="field">
      <%= form.label :foreign_transaction %>
      <%= form.check_box :foreign_transaction %>
    </div>
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/transactions/index.html.erb
<h1>Transactions</h1>
<%= link_to 'New Transaction', new_user_transaction_path(@user) %>
<ul>
  <% @transactions.each do |transaction| %>
    <li><%= transaction.amount %></li>
  <% end %>
</ul>
<%= link_to 'Back', users_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>
<%= render 'form' %>
<%= link_to 'Back', user_transactions_path(@user) %>

app/views/users/_form.html.erb
<%= form_with(model: @user) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render 'form' %>
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>All Users</h1>
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, user %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'form' %>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>User Profile</h1>
<p><strong>Name:</strong> <%= @user.name %></p>
<p><strong>Points:</strong> <%= @user.points %></p>
<p><strong>Points Expiration:</strong> <%= @user.points_expiration %></p>
<% if @user.tier == 'gold' %>
  <p>Congratulations! You have unlocked the Airport Lounge Access reward.</p>
<% end %>
<% if @quarterly_bonus_points_earned %>
  <p>Congratulations! You've earned 100 bonus points for spending greater than $2000 in this quarter.</p>
<% end %>